SELECT
    YEAR(DTYYYYMMDD)  AS Year,
    MONTH(DTYYYYMMDD) AS Month,
    AVG(CAST([CLOSE] AS DECIMAL(10,2)))   AS Avg_Index,
    STDEV(CAST([CLOSE] AS DECIMAL(10,2))) AS StdDev_Index
FROM Overall_Index
GROUP BY YEAR(DTYYYYMMDD), MONTH(DTYYYYMMDD)
ORDER BY Year, Month;
